version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:5000"
    env_file:
      - ../.env
    volumes:
      - ../uploads:/app/uploads
      - ../logs:/app/logs
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: flowerp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: